<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <RootNamespace>ragd</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="vec0.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="LLamaSharp" Version="0.27.0" />
    <PackageReference Include="LLamaSharp.Backend.Cuda12" Version="0.27.0" />
    <PackageReference Include="Markdig" Version="1.1.3" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
    <PackageReference Include="System.CommandLine" Version="2.0.9" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Service/Handlers/help.json" />
  </ItemGroup>
</Project>